"""drones table

Revision ID: dfe094de545f
Revises: 3d6bdf850d10
Create Date: 2023-04-02 16:14:38.989528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe094de545f'
down_revision = '3d6bdf850d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drones',
    sa.Column('id', sa.Text(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('model', sa.Enum('Lightweight', 'Middleweight', 'Cruiserweight', 'Heavyweight', name='modelenum'), nullable=True),
    sa.Column('weight_limit', sa.Integer(), nullable=False),
    sa.Column('battery_capacity', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('IDLE', 'LOADING', 'LOADED', 'DELIVERING', 'DELIVERED', 'RETURNING', name='stateenum'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drones_serial_number'), ['serial_number'], unique=True)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drone_id', sa.Text(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_medications_drone_id_drones'), 'drones', ['drone_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('drone_id')

    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drones_serial_number'))

    op.drop_table('drones')
    # ### end Alembic commands ###
